### ISSUE TITLE
Early stop with the attention model

### ISSUE THREAD

**Issue by korosig** [jsyoon0823/Time-series-prediction#2]
I must say I really like your solution. Your code is easy to understand and read. I am interested if you have any ideas on how to use Early stop in the basic_attention model?

**Comment by jsyoon0823** [comment]
Early stopping can be implemented by various methods.
(i) Using validation data and keep tracking the validation performance.
- Then, we stop training if the validation performance is no longer improved.

Actually, it is well implemented in Keras. You can get some ideas from the following link.
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping
