### ISSUE TITLE
better add doc: the model only take regression target value in [0, 1]

### ISSUE THREAD

**Issue by mw66** [jsyoon0823/Time-series-prediction#3]
https://github.com/jsyoon0823/Time-series-prediction/blob/478c76c8520538917ca369da92f25833c7f98da6/basic_attention.py#L187

In case of regression, the model actually only takes the output label in the range of [0, 1], since the outputs is coming from the `sigmoid` on:

https://github.com/jsyoon0823/Time-series-prediction/blob/478c76c8520538917ca369da92f25833c7f98da6/basic_attention.py#L175

I think the readme should add this note to make it clear; otherwise, people may feed any float number into the model as regression target, but obviously, that won't work.

**Comment by jsyoon0823** [comment]
Agreed. Normalization (with MinMax) is necessary on this. Will update this part. Thanks!
