### ISSUE TITLE
in basic_attention.py: `seq_len` is never used? should it be used as the look back window size of the attention?

### ISSUE THREAD

**Issue by mw66** [jsyoon0823/Time-series-prediction#4]
https://github.com/jsyoon0823/Time-series-prediction/blob/478c76c8520538917ca369da92f25833c7f98da6/basic_attention.py#L66

`seq_len` is never used?

should it be used as the look back window size of the attention?

**Comment by jsyoon0823** [comment]
If the size of the sequence is very long, yeah, we may use the look-back window.
